Repository futurismo-org/titan, pull requests merged in 2019-05, with the labels that each got.

#50 README追加
  README.md
Labels: WIP, Waiting For Review

#52 add base project
  firebase/.firebaserc
  firebase/.gitignore
  firebase/firebase.json
  firebase/functions/.eslintrc.json
  firebase/functions/.gitignore
  firebase/functions/index.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
  nextjs/.gitignore
  nextjs/README.md
  nextjs/components/head.js
  nextjs/components/nav.js
  nextjs/next.config.js
  nextjs/package.json
  nextjs/pages/index.js
  nextjs/static/favicon.ico
  nextjs/yarn.lock
Labels: LGTM

#55 Deploy設定
  firebase/yarn.lock
  nextjs/.firebaserc
  nextjs/.gitignore
  nextjs/firebase.json
  nextjs/next.config.js
  nextjs/package.json
Labels: LGTM

#56 GraphQLで情報取得
  .node-version
  .vscode/settings.json
  firebase/functions/.eslintignore
  firebase/functions/.eslintrc.js
  firebase/functions/.eslintrc.json
  firebase/functions/.prettierrc
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  firebase/functions/graphql/server.js
  firebase/functions/index.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/utils/admin.js
  firebase/functions/utils/config.js
  firebase/functions/yarn.lock
  firebase/yarn.lock
  nextjs/.eslintignore
  nextjs/.eslintrc.js
  nextjs/components/head.jsx
  nextjs/components/nav.jsx
  nextjs/lib/apollo.js
  nextjs/package.json
  nextjs/pages/index.jsx
  nextjs/pages/sample.jsx
  nextjs/yarn.lock
  package.json
Labels: LGTM

#61 ローカル疎通環境構築
  .gitignore
  Procfile
  firebase/functions/.eslintrc.js
  firebase/functions/utils/config.js
  nextjs/env.config.js
  nextjs/lib/apollo.js
  nextjs/next.config.js
  nextjs/package.json
  package.json
Labels: LGTM, Waiting For Review

#62 疎通確認 Mutation
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  firebase/functions/graphql/server.js
  nextjs/pages/index.jsx
Labels: LGTM

#66 認証の実装
  .node-version
  firebase/.eslintignore
  firebase/.eslintrc.js
  firebase/.gitignore
  firebase/.prettierrc
  firebase/functions/.gitignore
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  firebase/functions/index.js
  firebase/functions/package.json
  firebase/functions/user.js
  firebase/functions/utils/admin.js
  firebase/functions/utils/firebase.js
  firebase/functions/yarn.lock
  nextjs/.eslintrc.js
  nextjs/lib/config.js
  nextjs/lib/firebase.js
  nextjs/next.config.js
  nextjs/package.json
  nextjs/pages/signin.jsx
  nextjs/yarn.lock
Labels: WIP

#67 チャレンジ個別表示
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  nextjs/.gitignore
  nextjs/components/atoms/.keep
  nextjs/components/molecules/.keep
  nextjs/components/molecules/Header.jsx
  nextjs/components/organisms/.keep
  nextjs/components/templates/.keep
  nextjs/components/templates/MyLayout.jsx
  nextjs/config-export.js
  nextjs/env.config.js
  nextjs/firebase.json
  nextjs/functions/.gitignore
  nextjs/functions/index.js
  nextjs/functions/package.json
  nextjs/next.config.js
  nextjs/package.json
  nextjs/pages/challenge.jsx
  nextjs/pages/challenges.jsx
  nextjs/pages/index.jsx
  nextjs/queries/challenges-query.js
  nextjs/routes.js
  nextjs/server.js
  nextjs/yarn.lock
Labels: WIP

#71 チャレンジ表示
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  reactjs/package.json
  reactjs/src/components/molecules/ChallengeBody.jsx
  reactjs/src/components/molecules/ChallengeDIscussion.jsx
  reactjs/src/components/molecules/ChallengeHeader.jsx
  reactjs/src/components/molecules/ChallengeLeaderBoard.jsx
  reactjs/src/components/molecules/ChallengeNavbar.jsx
  reactjs/src/components/molecules/ChallengeOverview.jsx
  reactjs/src/components/molecules/ChallengeRules.jsx
  reactjs/src/components/organisms/Challenge.jsx
  reactjs/src/components/organisms/Challenges.jsx
  reactjs/src/components/organisms/DashBoard.jsx
  reactjs/src/index.jsx
  reactjs/src/lib/apollo.js
  reactjs/yarn.lock
Labels: LGTM

#72 マテリアルUI導入
  reactjs/package.json
  reactjs/src/components/molecules/ChallengeHeader.jsx
  reactjs/src/components/molecules/Footer.jsx
  reactjs/src/components/molecules/Header.jsx
  reactjs/src/components/molecules/NavToolbar.jsx
  reactjs/src/components/molecules/TopToolbar.jsx
  reactjs/src/components/molecules/challenges/ChallengeBody.jsx
  reactjs/src/components/molecules/challenges/ChallengeDIscussion.jsx
  reactjs/src/components/molecules/challenges/ChallengeHeader.jsx
  reactjs/src/components/molecules/challenges/ChallengeLeaderBoard.jsx
  reactjs/src/components/molecules/challenges/ChallengeNavbar.jsx
  reactjs/src/components/molecules/challenges/ChallengeOverview.jsx
  reactjs/src/components/molecules/challenges/ChallengeRules.jsx
  reactjs/src/components/organisms/App.jsx
  reactjs/src/components/organisms/Challenge.jsx
  reactjs/src/components/organisms/Challenges.jsx
  reactjs/src/components/templates/DefaultLayout.jsx
  reactjs/src/components/templates/Head.jsx
  reactjs/src/index.jsx
  reactjs/src/lib/apollo.js
  reactjs/src/lib/theme.js
  reactjs/yarn.lock
Labels: LGTM

#78 チャレンジ詳細のタブメニュー作成
  reactjs/src/components/molecules/Footer.jsx
  reactjs/src/components/molecules/challenges/ChallengeBody.jsx
  reactjs/src/components/molecules/challenges/ChallengeNavbar.jsx
  reactjs/src/components/organisms/Challenge.jsx
  reactjs/src/components/organisms/Challenges.jsx
Labels: LGTM

#79 チャレンジ一覧のデザインを当てる
  reactjs/src/components/atoms/ChallengeCard.jsx
  reactjs/src/components/molecules/challenges/ChallengeBody.jsx
  reactjs/src/components/organisms/Challenges.jsx
Labels: LGTM

#84 チャレンジ管理(admin)
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  package.json
  reactjs/.eslintignore
  reactjs/.eslintrc.js
  reactjs/package.json
  reactjs/src/components/atoms/ChallengeCard.jsx
  reactjs/src/components/molecules/challenges/ChallengeHeader.jsx
  reactjs/src/components/organisms/Challenge.jsx
  reactjs/src/components/organisms/Challenges.jsx
  reactjs/src/components/organisms/admin/Admin.jsx
  reactjs/src/components/organisms/admin/ChallengeForm.jsx
  reactjs/src/components/organisms/admin/Challenges.jsx
  reactjs/src/components/organisms/admin/DashBoard.jsx
  reactjs/yarn.lock
  yarn.lock
Labels: WIP

#88 ファイルの整理
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc
  .vscode/settings.json
  .vscode/tasks.json
  firebase/.eslintrc.js
  firebase/.vscode/settings.json
  firebase/.vscode/tasks.json
  firebase/README.md
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/package.json
  firebase/functions/yarn.lock
  package.json
  reactjs/.vscode/settings.json
  reactjs/.vscode/tasks.json
  reactjs/README.md
  reactjs/package.json
  reactjs/src/components/atoms/ChallengeCard.jsx
  reactjs/src/components/molecules/Footer.jsx
  reactjs/src/components/molecules/Header.jsx
  reactjs/src/components/molecules/NavToolbar.jsx
  reactjs/src/components/molecules/TopToolbar.jsx
  reactjs/src/components/molecules/challenges/ChallengeBody.jsx
  reactjs/src/components/molecules/challenges/ChallengeDIscussion.jsx
  reactjs/src/components/molecules/challenges/ChallengeHeader.jsx
  reactjs/src/components/molecules/challenges/ChallengeLeaderBoard.jsx
  reactjs/src/components/molecules/challenges/ChallengeNavbar.jsx
  reactjs/src/components/molecules/challenges/ChallengeOverview.jsx
  reactjs/src/components/molecules/challenges/ChallengeRules.jsx
  reactjs/src/components/organisms/App.jsx
  reactjs/src/components/organisms/Challenge.jsx
  reactjs/src/components/organisms/Challenges.jsx
  reactjs/src/components/organisms/DashBoard.jsx
  reactjs/src/components/organisms/Home.jsx
  reactjs/src/components/organisms/PlayGround.jsx
  reactjs/src/components/organisms/Signin.jsx
  reactjs/src/components/organisms/admin/Admin.jsx
  reactjs/src/components/organisms/admin/ChallengeForm.jsx
  reactjs/src/components/organisms/admin/Challenges.jsx
  reactjs/src/components/organisms/admin/DashBoard.jsx
  reactjs/src/components/templates/AdminLayout.jsx
  reactjs/src/components/templates/DefaultLayout.jsx
  reactjs/src/components/templates/Head.jsx
  reactjs/src/index.jsx
  reactjs/src/lib/apollo.js
  reactjs/src/lib/config.js
  reactjs/src/lib/firebase.js
  reactjs/src/lib/theme.js
  reactjs/src/sample/index.js
  reactjs/yarn.lock
  titan.code-workspace
  yarn.lock
Labels: LGTM

#91 カテゴリページ
  firebase/functions/graphql/data/resolvers.js
  firebase/functions/graphql/data/schema.js
  package-lock.json
  reactjs/src/components/atoms/CategoryCard.jsx
  reactjs/src/components/molecules/categories/CategoryBody.jsx
  reactjs/src/components/molecules/categories/CategoryDIscussion.jsx
  reactjs/src/components/molecules/categories/CategoryHeader.jsx
  reactjs/src/components/molecules/categories/CategoryLeaderBoard.jsx
  reactjs/src/components/molecules/categories/CategoryNavbar.jsx
  reactjs/src/components/molecules/categories/CategoryOverview.jsx
  reactjs/src/components/molecules/categories/CategoryRules.jsx
  reactjs/src/components/organisms/Categories.jsx
  reactjs/src/components/organisms/Category.jsx
  reactjs/src/components/organisms/Home.jsx
  titan.code-workspace
Labels: LGTM

#100 seedスクリプトの追加
  firebase/functions/bin/db_clear.sh
  firebase/functions/bin/db_seeds.sh
  firebase/functions/package.json
  firebase/functions/src/cli/seeds.ts
  firebase/functions/yarn.lock
Labels: LGTM

#102 認証機能の強化 part2
  Procfile
  firebase/functions/tsconfig.json
  reactjs/.eslintrc.js
  reactjs/package.json
  reactjs/public/anonymous.png
  reactjs/src/components/atoms/AuthButton.tsx
  reactjs/src/components/atoms/AuthModal.tsx
  reactjs/src/components/atoms/LoginForm.tsx
  reactjs/src/components/atoms/SignUpForm.tsx
  reactjs/src/components/atoms/UserItem.tsx
  reactjs/src/components/molecules/NavigationItem.tsx
  reactjs/src/components/molecules/TopToolbar.tsx
  reactjs/src/components/organisms/Home.tsx
  reactjs/src/components/organisms/Signin.tsx
  reactjs/src/containers/authContainer.ts
  reactjs/src/index.tsx
  reactjs/src/lib/firebase.ts
  reactjs/src/reducers/index.ts
  reactjs/src/store.ts
  reactjs/tsconfig.json
  reactjs/yarn.lock
Labels: LGTM

#109 カテゴリ個別ページエラー
  reactjs/src/components/organisms/Categories.tsx
Labels: LGTM

#110 カテゴリ系のTypeScript化
  reactjs/src/components/atoms/CategoryCard.tsx
  reactjs/src/components/molecules/categories/CategoryBody.tsx
  reactjs/src/components/molecules/categories/CategoryDiscussion.jsx
  reactjs/src/components/molecules/categories/CategoryDiscussion.tsx
  reactjs/src/components/molecules/categories/CategoryHeader.tsx
  reactjs/src/components/molecules/categories/CategoryLeaderBoard.jsx
  reactjs/src/components/molecules/categories/CategoryLeaderBoard.tsx
  reactjs/src/components/molecules/categories/CategoryNavbar.tsx
  reactjs/src/components/molecules/categories/CategoryOverview.jsx
  reactjs/src/components/molecules/categories/CategoryOverview.tsx
  reactjs/src/components/molecules/categories/CategoryRules.jsx
  reactjs/src/components/molecules/categories/CategoryRules.tsx
  reactjs/src/components/molecules/challenges/ChallengeNavbar.tsx
  reactjs/src/components/organisms/Categories.tsx
  reactjs/src/components/organisms/Challenge.tsx
  reactjs/tsconfig.json
Labels: LGTM

#111 Dashboard
  reactjs/package.json
  reactjs/src/components/molecules/DashBoardPaper.tsx
  reactjs/src/components/organisms/DashBoard.tsx
  reactjs/yarn.lock
Labels: LGTM

#114 カテゴリとチャレンジ見直し
  firebase/functions/bin/db_clear.sh
  firebase/functions/bin/db_seeds.sh
  firebase/functions/src/cli/seeds.ts
Labels: LGTM

#117 管理画面の入力フォーム
  package.json
  reactjs/src/components/molecules/challenges/ChallengeBody.tsx
  reactjs/src/components/molecules/challenges/ChallengeOverview.tsx
  reactjs/src/components/molecules/challenges/ChallengeRules.tsx
  reactjs/src/components/organisms/Challenge.tsx
  reactjs/src/components/organisms/admin/ChallengeForm.tsx
  yarn.lock
Labels: LGTM

#119 チャレンジ参加
  firebase/functions/src/user.ts
  reactjs/src/components/atoms/AuthModal.tsx
  reactjs/src/components/atoms/JoinButton.tsx
  reactjs/src/components/atoms/UserItem.tsx
  reactjs/src/components/molecules/NavigationItem.tsx
  reactjs/src/components/molecules/challenges/ChallengeHeader.tsx
Labels: LGTM
